# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-10 04:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sitters', '0002_auto_20170708_0257'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Reviews',
            new_name='Review',
        ),
        migrations.RemoveField(
            model_name='sitter',
            name='rating',
        ),
        migrations.AddField(
            model_name='sitter',
            name='overall_rank',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='sitter',
            name='rating_score',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='sitter',
            name='sitter_score',
            field=models.FloatField(default=0),
        ),
    ]
